### ISSUE TITLE
Example site should have hash_bookmark=true set

### ISSUE THREAD

**Issue by paul-hammant** [thecdil/timelinejs-template#10]
See http://timeline.knightlab.com/docs/options.html

https://thecdil.github.io/timelinejs-template#event-good-news-power would be what's shown for the 1947 entry.

**Comment by evanwill** [comment]
@paul-hammant the template has the hash bookmark option available by using front matter, see "Advanced Options" section, https://github.com/thecdil/timelinejs-template/blob/main/docs/timeline.md

**Comment by paul-hammant** [comment]
I'm not talking generally about hash bookmarks as an option. I'm saying for the GitHub-Pages deployment - https://thecdil.github.io/timelinejs-template - specifically. As an interactive showcase, that demo should have it enabled so people can see it as a feature.

**Comment by paul-hammant** [comment]
Meaning, I'm driving people to your template saying "you should use this for your cause", but the coupled demo site isn't showing off all the features of TimelineJS3

**Comment by evanwill** [comment]
hash_bookmark is enabled on the home page example now, and just tweaked the demo data a bit. Eventually will probably flesh out more, but the whole thing is still pretty drafty.

**Comment by paul-hammant** [comment]
Yay!  https://thecdil.github.io/timelinejs-template/#event-pgood-news-power-p  ... though I'm not sure what the 'p' is encoding that's hidden

**Comment by evanwill** [comment]
oh man-- i see where the p is from... 
I have the headline and text values going through the "markdownify" filter, because I want to be able to use markdown in the values. Unfortunately that ended up making each value enclosed in <p></p> (I didn't think that happened unless you had blank lines)--so then timelinejs is sanitizing the headline into the hash value, 
e.g. `<p>Good News - Power</p>` becomes `p-good-news-power-p`

but that also made me realize the styling is all slightly off because the <p>'s are inside the elements timelinejs is trying to style.

hacky solution for now, swapped out `| markdownify` with `| markdownify | remove: '<p>' | remove: '</p>'`, which should work as expected, rendering the inline markdown, but not creating p's.
