### ISSUE TITLE
default layout should include commit hash as a HTML comment

### ISSUE THREAD

**Issue by paul-hammant** [thecdil/timelinejs-template#3]
That's {{ site.github.build_revision.}} 

People using the template can make the same var visible if they want to.

**Comment by paul-hammant** [comment]
** Merkle trees for democracy!! **

**Comment by evanwill** [comment]
@paul-hammant I can confirm that `{{ site.github.build_revision }}` does work to grab the commit hash (although github does not seem to officially document the github object any more). 

However, I hesitate to use the site.github object because it is only available during github pages build, so you won't have it when using jekyll locally or hosting somewhere else. Also I don't know that users of this super basic template are interested in having git hashes exposed--advanced users will probably want to customize the template extensively anyway. This is just a quick starting point. 
You mentioned [jekyll-git-hash](https://github.com/yegor256/jekyll-git-hash/blob/master/jekyll-git-hash.rb) plugin, which folks seemed to be using the hash to add a version tag to their assets. You could use that plugin if you build your site using a github action (or manually) instead of default gh-pages build.
